[build]
  publish = "front/views"  # Adjust this if your HTML files are somewhere else
  command = "npm install && npm run build"  # If you have a build step

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
