[build]
  publish = "front/views"  # This should point to the directory containing your index.html
  command = "npm run build"  # Or adjust based on your actual build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
